version: '3'
services:
  turbo-dollop:
    build: .
    privileged: true
    restart: unless-stopped
    ports:
      # bind on our 5000 port because most people have 80, 8080 already bound
      - "5015:5000"
